-- ===========================================================================
-- R__sp_register_payment.sql
--
-- Procedimiento que cobranza invoca al registrar el pago de una factura.
-- Aplica el recargo por mora si corresponde, actualiza el saldo y el medio de
-- pago, y deja constancia del cambio en policy_edit_log — en una sola unidad.
-- ===========================================================================

-- ¿Por qué se aplica DESPUÉS de R__fn_calculate_late_fee, si Flyway no sabe
-- que uno depende del otro? Porque los repeatables se aplican en orden
-- alfabético por descripción, y "fn_calculate_late_fee" < "sp_register_payment".
-- Es una dependencia que funciona por suerte tipográfica y por eso es frágil:
-- si mañana la función se renombra, este script podría fallar por ejecutarse
-- antes. Cuando el orden importa de verdad, se fuerza con
-- `flyway.repeatableSqlMigrationPrefix` o con un prefijo numérico propio
-- (R__01_fn..., R__02_sp...).

CREATE OR REPLACE PROCEDURE sp_register_payment(
    p_bill_id        INTEGER,
    p_monto_pagado   NUMERIC,
    p_payment_method TEXT,
    p_editado_por    TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_policy_id      INTEGER;
    v_balance_actual NUMERIC;
    v_due_date       DATE;
    v_dias_atraso    INTEGER;
    v_recargo_tasa   NUMERIC(4,3);
    v_recargo_monto  NUMERIC(10,2);
    v_nuevo_balance  NUMERIC(10,2);
    v_log_id         INTEGER;
BEGIN
    -- Validar antes de escribir. Sin esto, la foreign key también rechazaría
    -- la actualización, pero con un mensaje del motor que no le dice nada a
    -- quien llamó.
    SELECT policy_id, balance, due_date
      INTO v_policy_id, v_balance_actual, v_due_date
      FROM bill
     WHERE id = p_bill_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'La factura % no existe', p_bill_id
            USING HINT = 'Verifica el bill_id contra la tabla bill.';
    END IF;

    IF p_monto_pagado <= 0 THEN
        RAISE EXCEPTION 'El monto pagado debe ser mayor a cero.';
    END IF;

    v_dias_atraso  := GREATEST(CURRENT_DATE - v_due_date, 0);
    v_recargo_tasa := fn_calculate_late_fee(v_dias_atraso, v_balance_actual);
    v_recargo_monto := ROUND(v_balance_actual * v_recargo_tasa, 2);

    v_nuevo_balance := GREATEST(v_balance_actual + v_recargo_monto - p_monto_pagado, 0);

    -- Esta es la línea que revienta cuando cobranza empieza a mandar el medio
    -- de pago real ("credit_card") en vez del código interno de dos letras:
    -- payment_method todavía es VARCHAR(2) en este punto de la historia.
    UPDATE bill
       SET balance        = v_nuevo_balance,
           status          = CASE WHEN v_nuevo_balance = 0 THEN 'Paid' ELSE status END,
           payment_method  = p_payment_method
     WHERE id = p_bill_id;

    -- Mismo patrón —y misma deuda documentada— que en la Sesión 2: el id se
    -- calcula con MAX(id)+1 porque policy_edit_log se cargó en la Sesión 1
    -- con ids explícitos, sin secuencia asociada. No apto para concurrencia;
    -- la migración correcta (GENERATED BY DEFAULT AS IDENTITY) queda como
    -- ejercicio pendiente, igual que en el dataset de referencia.
    SELECT COALESCE(MAX(id), 0) + 1 INTO v_log_id FROM policy_edit_log;

    INSERT INTO policy_edit_log (id, policy_id, edited_table_name, edited_date, additional_info, edited_by)
    VALUES (
        v_log_id, v_policy_id, 'Bill', now(),
        format('Pago de %s registrado vía %s. Recargo por mora: %s (%s dias). Nuevo saldo: %s',
               p_monto_pagado, p_payment_method, v_recargo_monto, v_dias_atraso, v_nuevo_balance),
        p_editado_por
    );

    RAISE NOTICE 'Factura % actualizada: recargo %, nuevo saldo %', p_bill_id, v_recargo_monto, v_nuevo_balance;
END;
$$;

-- ¿Por qué PROCEDURE y no FUNCTION? Un procedure se invoca con CALL y puede
-- manejar transacciones en su interior; una función corre siempre dentro de
-- la transacción de quien la llama. Para algo que escribe en dos tablas,
-- PROCEDURE es la herramienta correcta.

COMMENT ON PROCEDURE sp_register_payment(INTEGER, NUMERIC, TEXT, TEXT) IS
    'Registra el pago de una factura con recargo por mora y deja constancia en policy_edit_log.';
