CREATE WAREHOUSE IF NOT EXISTS WH_VEHICLE_COVERGE
    WAREHOUSE_SIZE      = 'XSMALL'
    AUTO_SUSPEND        = 60
    AUTO_RESUME         = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT             = 'Warehouse para estructura de datos del caso de seguro de vehiculos';

CREATE DATABASE IF NOT EXISTS VEHICLE_COVERAGE
    COMMENT = 'Data Warehouse del caso de seguro de vehiculos';

CREATE SCHEMA IF NOT EXISTS VEHICLE_COVERAGE.RAW
    COMMENT = 'Landing zone: datos extraídos de Neon, sin transformar';


CREATE ROLE IF NOT EXISTS TEAM5_LOADER
    COMMENT = 'Rol de servicio para ELT. Sin privilegios de administración.';

GRANT USAGE ON WAREHOUSE WH_VEHICLE_COVERGE TO ROLE TEAM5_LOADER;
GRANT USAGE ON DATABASE VEHICLE_COVERAGE TO ROLE TEAM5_LOADER;
GRANT USAGE, CREATE TABLE ON SCHEMA VEHICLE_COVERAGE.RAW TO ROLE TEAM5_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA VEHICLE_COVERAGE.RAW TO ROLE TEAM5_LOADER;

GRANT ROLE TEAM5_LOADER TO USER <JAYMARM>;

USE WAREHOUSE WH_VEHICLE_COVERGE;
USE DATABASE VEHICLE_COVERAGE;
USE SCHEMA RAW;

-- ----------------------------------------------------------------------------
-- Verificación
-- ----------------------------------------------------------------------------
SHOW WAREHOUSES LIKE 'WH_VEHICLE_COVERGE';
SHOW SCHEMAS IN DATABASE VEHICLE_COVERAGE;
SHOW GRANTS TO ROLE TEAM5_LOADER;
